sonar.projectKey=ThembalethuNdlovu_PaymentsPortal
sonar.organization=thembalethundlovu
sonar.projectName=PaymentsPortal
sonar.projectVersion=1.0
sonar.sources=server
sonar.exclusions=**/node_modules/**,**/build/**,**/*.test.js
sonar.sourceEncoding=UTF-8