version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install Server Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run Security Audit
          command: npm audit --audit-level=critical || true

      - sonarcloud/scan

workflows:
  build-test-scan:
    jobs:
      - build-and-test:
          context: SonarCloud